name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: List dir
      run: dir
      
    - name: Cache LLVM build
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: D:/a/TortLanguage/TortLanguage/llvmBuild
        key: llvm-build-${{ runner.os }}-msvc-${{ hashFiles('llvm/CMakeLists.txt') }}
    - name: create llvmProject
      run: mkdir llvmProject
      
    - name: List dir
      run: dir
        
    - name: Clone LLVM repository
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        path: D:/a/TortLanguage/TortLanguage/llvmProject
        repository: llvm/llvm-project
        ref: llvmorg-16.0.0
    
    - name: List dir
      run: dir

    - name: Build LLVM
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DLLVM_ENABLE_PROJECTS="llvm;lld" D:/a/TortLanguage/TortLanguage/llvmBuild/llvm
        cmake --build . --config Release
    
    - name: List dir
      run: dir
    
    - name: Get llvmBuild path
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      run: |
          mkdir D:/a/TortLanguage/TortLanguage/llvmBuild
          cmake -DCMAKE_INSTALL_PREFIX=D:/a/TortLanguage/TortLanguage/llvmBuild -P cmake_install.cmake
    - name: List dir
      run: dir
